### PR TITLE
Fix serialized attributes updated at

### PR DESCRIPTION
**Pull request by quainjn**

### CODE REVIEW

**Comment by dimroc** [comment]
I was going to suggest taking a hash of the serialized contents to track whether or not it has changed because of the overhead involved when holding onto an original copy. But unfortunately, someone tried that (https://github.com/rails/rails/pull/13428). Maybe his implementation sucked though and it's worth a second try. 

You can imagine the cost involved when you have a large deep hash to be serialized.

I've addressed my other concerns inline in the code.

**Comment by matthuhiggins** [comment]
I believe the best implementation, if it's going to be done, is to evaluate `changed_attributes` at the time of calling the method, rather than tracking it when writing attributes. This would use the Object#hash method. This code would go into active_model/dirty.rb, and then all special casing would be removed from active_record.

Otherwise, I think that the code to always write serialized columns should flat out be removed.

**Comment by dimroc** [comment]
Just wanted to reiterate what we discussed in person:
1. `hash.deep_dup/clone` is unreliable and `marshal.dump` is too costly.
2. take the hash to check for changes seems the best bet but has been tried before and will make the `_was` and other activerecord methods unavailable. People seem fine with that, it probably doesn't work now. But you should definitely check that.
3. Definitely read the last 10 or so comments here (https://github.com/rails/rails/issues/8328). They were made only 2 months ago and cover exactly what you are doing.
4. Compare your commit to this guy's https://github.com/rails/rails/pull/13428

**Comment by matthuhiggins** [comment]
In your own code, you have some alternatives to avoid the problem:
- Don't use serialization at all. Simply add a text column, and wrap the reader and writer methods. ie.

``` ruby
def stuff=(value)
  self[:stuff] = value.to_json
end

def stuff
  ActiveSupport::JSON.decode self[:stuff]
end
```
- If you've got a posgres db, use the native hstore, array or json types. Much, much faster and serialization happens in the adapter layer rather than AR layer.

**Pull request closed without merging**
